apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: blu-reserve-backend
  namespace: blu-reserve
  labels:
    app: blu-reserve
    component: backend
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: blu-reserve-frontend
  namespace: blu-reserve
  labels:
    app: blu-reserve
    component: frontend
spec:
  lookupPolicy:
    local: true
